머신러닝 ㅗㅇ류
[INFO] shooter_A. Step: 360000. Time Elapsed: 46.821 s. Mean Reward: 30.485. Std of Reward: 6.620. Training.
[INFO] Infantry_A. Step: 360000. Time Elapsed: 46.862 s. Mean Reward: 23.999. Std of Reward: 1.553. Training.
[WARNING] Restarting worker[0] after 'The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.
         If you're running on a headless server without graphics support, turn off display by either passing --no-graphics option or build your Unity executable as server build.'
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[ERROR] UnityEnvironment worker 0: environment raised an unexpected exception.
Traceback (most recent call last):
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 163, in worker
    env = env_factory(worker_id, side_channels)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 192, in create_unity_environment
    log_folder=log_folder,
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\environment.py", line 245, in __init__
    aca_params.package_version,
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\environment.py", line 96, in _check_communication_compatibility
    if unity_communicator_version.version[0] == 0:
AttributeError: 'StrictVersion' object has no attribute 'version'
[WARNING] Trainer has multiple policies, but default behavior only saves the first.
[WARNING] Trainer has multiple policies, but default behavior only saves the first.
c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\torch\onnx\symbolic_opset9.py:4322: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  + "or define the initial states (h0/c0) as inputs of the model. "
c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\torch\onnx\utils.py:688: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  graph, params_dict, GLOBALS.export_onnx_opset_version
c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\torch\onnx\utils.py:1179: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  graph, params_dict, GLOBALS.export_onnx_opset_version
[INFO] Exported results\ustom_shooter_C\shooter_A\shooter_A-364482.onnx
[INFO] Copied results\ustom_shooter_C\shooter_A\shooter_A-364482.onnx to results\ustom_shooter_C\shooter_A.onnx.
[WARNING] Trainer has multiple policies, but default behavior only saves the first.
[WARNING] Trainer has multiple policies, but default behavior only saves the first.
[INFO] Exported results\ustom_shooter_C\Infantry_A\Infantry_A-364482.onnx
[INFO] Copied results\ustom_shooter_C\Infantry_A\Infantry_A-364482.onnx to results\ustom_shooter_C\Infantry_A.onnx.
Traceback (most recent call last):
  File "c:\users\happy\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python37\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 260, in main
    run_cli(parse_command_line())
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 256, in run_cli
    run_training(run_seed, options, num_areas)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 132, in run_training
    tc.start_learning(env_manager)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 176, in start_learning
    n_steps = self.advance(env_manager)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 234, in advance
    new_step_infos = env_manager.get_steps()
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\env_manager.py", line 124, in get_steps
    new_step_infos = self._step()
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 420, in _step
    self._restart_failed_workers(step)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 328, in _restart_failed_workers
    self.reset(self.env_parameters)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 446, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "c:\users\happy\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 101, in recv
    raise env_exception
AttributeError: 'StrictVersion' object has no attribute 'version'